### ISSUE TITLE
lab0/实验环境配置.md 中1.3 riscv64 工具链中PATH的配置有误

### ISSUE THREAD

**Issue by nmrenyi** [DeathWish5/ucore-Tutorial-Book#1]
安装riscv64-unknown-elf-gcc和安装musl-gcc时，配置PATH的命令应该是export PATH="/usr/local/riscv64-unknown-elf-gcc/bin:$PATH"和export PATH="/usr/local/riscv64-linux-musl-cross/bin:$PATH"

**Comment by nzpznk** [comment]
多谢指出！已修复
